import type { Material } from "@/lib/types";

const asset = (
  file: string,
  alt: string,
  dominantTone: Material["visual"]["dominantTone"],
  size = 800,
) => ({
  id: file.replace(/\.svg$/, ""),
  src: `/images/placeholders/${file}`,
  alt,
  width: size,
  height: size,
  type: "illustration" as const,
  dominantTone,
  isPlaceholder: true,
});

export const materials: Material[] = [
  {
    id: "golden-beads",
    slug: "golden-beads",
    name: "Golden Beads",
    category: "math",
    paradigm: "montessori",
    ageBand: "3-6",
    description: "Loose and strung bead quantities from 1 to 1000, making the decimal system touchable.",
    visual: asset("mc-montessori-material-golden-beads-800.svg", "Golden bead material used to explore units, tens, hundreds and thousands.", "clay"),
  },
  {
    id: "pink-tower",
    slug: "pink-tower",
    name: "Pink Tower",
    category: "sensorial",
    paradigm: "montessori",
    ageBand: "3-6",
    description: "Ten pink cubes graded by size, refining visual discrimination and grip.",
    visual: asset("mc-montessori-material-pink-tower-800.svg", "Ten graduated pink cubes stacked from largest to smallest.", "clay"),
  },
  {
    id: "sandpaper-letters",
    slug: "sandpaper-letters",
    name: "Sandpaper Letters",
    category: "language",
    paradigm: "montessori",
    ageBand: "3-6",
    description: "Textured letterforms traced with two fingers to link sound, shape and movement.",
    visual: asset("mc-montessori-material-sandpaper-letters-800.svg", "Sandpaper letter card traced with two fingers.", "wood"),
  },
  {
    id: "sound-cylinders",
    slug: "sound-cylinders",
    name: "Sound Cylinders",
    category: "sensorial",
    paradigm: "montessori",
    ageBand: "3-6",
    description: "Sealed cylinder pairs matched by ear, sharpening auditory discrimination.",
    visual: asset("mc-montessori-material-sound-cylinders-800.svg", "Paired sound cylinders shaken and matched by listening.", "clay"),
  },
  {
    id: "globe-landform",
    slug: "globe-landform",
    name: "Globe & Landform Tray",
    category: "nature",
    paradigm: "montessori",
    ageBand: "3-6",
    description: "A textured globe and land-and-water tray for the Culture & Science area, placing the child inside a larger world.",
    visual: asset("mc-montessori-material-globe-800.svg", "Textured globe used to explore continents and oceans by touch.", "leaf"),
  },
  {
    id: "wooden-abacus",
    slug: "wooden-abacus",
    name: "Wooden Abacus",
    category: "math",
    paradigm: "vedic",
    ageBand: "6-9",
    description: "An optional tactile aid for mental mathematics, used after — never instead of — number-pattern understanding.",
    visual: asset("mc-vedic-material-wooden-abacus-800.svg", "Wooden abacus used as a tactile aid for mental mathematics.", "saffron"),
  },
  {
    id: "nature-collection-tray",
    slug: "nature-collection-tray",
    name: "Nature Collection Tray",
    category: "nature",
    paradigm: "integrated",
    ageBand: "3-6",
    description: "Leaves, seeds and stones gathered on a walk, sorted and observed at a low shelf.",
    visual: asset("mc-shared-material-nature-tray-800.svg", "A tray of collected leaves, seeds and stones for sorting and observation.", "leaf"),
  },
  {
    id: "pouring-set",
    slug: "pouring-set",
    name: "Pouring Set",
    category: "practical",
    paradigm: "montessori",
    ageBand: "18m-3",
    description: "Two small jugs sized for little hands, used to practise controlled pouring.",
    visual: asset("mc-montessori-material-pouring-set-800.svg", "Two small ceramic jugs used for practising controlled pouring.", "wood"),
  },
  {
    id: "rhythm-cards",
    slug: "rhythm-cards",
    name: "Daily Rhythm Cards",
    category: "rhythm",
    paradigm: "vedic",
    ageBand: "3-6",
    description: "Simple sunrise-to-sunset picture cards a family arranges to build their own daily sequence.",
    visual: asset("mc-vedic-material-rhythm-cards-800.svg", "Illustrated cards representing moments in a sunrise-to-sunset daily rhythm.", "sky"),
  },
];

export function getMaterialById(id: string): Material | undefined {
  return materials.find((material) => material.id === id);
}
